clusterSecretStore:
  name: aws-secrets-manager
  region: us-east-1
  serviceAccount:
    name: external-secrets
    namespace: external-secrets

operator:
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::459063349398:role/ExternalSecretsRole
