apiVersion: v1
kind: ConfigMap
metadata:
  name: jobdsl-scripts
  namespace: {{ .Release.Namespace }}
data:
  {{- range .Values.jenkins.jobdsls }}
  {{ .name }}.groovy: |
  {{ $.Files.Get .file | nindent 4 }}
  {{- end }}