apiVersion: v2
name: traefik
description: An traefik Helm chart
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
- name: traefik
  version: 37.1.1
  repository: https://traefik.github.io/charts