{{- if .Values.externalSecrets.github.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jenkins-staging-github-oauth-credential
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: jenkins-staging-github-oauth-credential
    creationPolicy: Owner
  data:
  - secretKey: clientId
    remoteRef:
      key: {{ .Values.externalSecrets.github.secretPath }}
      property: clientId
  - secretKey: clientSecret
    remoteRef:
      key: {{ .Values.externalSecrets.github.secretPath }}
      property: clientSecret
{{- end }}
