apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jenkins-prod-github-oauth-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: jenkins-prod-github-oauth-secret
    creationPolicy: Owner
  data:
  - secretKey: clientId
    remoteRef:
      key: "jenkins/production/github/oauth"
      property: clientId
  - secretKey: clientSecret
    remoteRef:
      key: "jenkins/production/github/oauth"
      property: clientSecret
