apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-eventsource
  namespace: argo-events
spec:
  rules:
    - host: minio-events.neikoscloud.net
      http:
        paths:
          - path: /events
            pathType: Prefix
            backend:
              service:
                name: minio-dataset-daily-eventsource-svc
                port:
                  number: 12000