jenkins:
  controller:
    image: "jenkins/jenkins"
    tag: "jdk21"
    resources:
      requests:
        cpu: "500m"
        memory: "1024Mi"
      limits:
        cpu: "1000m"
        memory: "2048Mi"
    serviceType: Nodeport
    Nodeport: 30000
    persistence:
      enabled: true
      size: "8Gi"
      storageClass: ""
    
    installPlugins:
      - kubernetes:1.36.4
      - workflow-aggregator:2.7
      - git:4.15.3
      - configuration-as-code:1.63.0
      - blueocean:1.26.3

    
    JCasC:
      defaultConfig: true
      configScripts:
        welcome-message: |
          jenkins:
            systemMessage: "welcome to Jenkins"